var LANGUAGES = {
  "en": { "name": "English", "flag": "🇬🇧", "t": {
    "subtitle": "Find and download .manifest files from any Steam game",
    "search_placeholder": "Steam App ID (e.g. 730)",
    "fetch_btn": "Fetch",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Enter an App ID to search for .manifest files in ManifestHub.",
    "welcome_sub": "Supports over 62,000 games and DLCs.",
    "popular_label": "Popular:",
    "trending_title": "Trending Games",
    "loading": "Searching for manifests...",
    "not_found": "No manifests found for App ID",
    "not_found_hint": "They may not be available for this game yet. Please wait for their release.",
    "download_all": "Download All (.zip)",
    "downloading": "Downloading...",
    "manifests": "manifest(s)",
    "sources": "source(s)",
    "btn_download": "Download",
    "footer": "Manifest files sourced from ManifestHub (GitHub). We do not host files directly.",
    "dl_toast": "All files downloaded successfully.",
    "search": "Search",
    "games": "Games",
    "language": "Language",
    "invalid_id": "Enter a valid App ID.",
    "error_search": "Search error.",
    "jszip_error": "JSZip failed to load. Reload the page."
  }},
  "es": { "name": "Español", "flag": "🇪🇸", "t": {
    "subtitle": "Busca y descarga archivos .manifest de cualquier juego de Steam",
    "search_placeholder": "Steam App ID (ej: 730)",
    "fetch_btn": "Buscar",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Ingresa un App ID para buscar archivos .manifest en ManifestHub.",
    "welcome_sub": "Soporta mas de 62,000 juegos y DLCs.",
    "popular_label": "Populares:",
    "trending_title": "Juegos en Tendencia",
    "loading": "Buscando manifests...",
    "not_found": "No se encontraron manifests para el App ID",
    "not_found_hint": "Es posible que aun no esten disponibles para este juego.",
    "download_all": "Descargar Todo (.zip)",
    "downloading": "Descargando...",
    "manifests": "manifest(s)",
    "sources": "fuente(s)",
    "btn_download": "Descargar",
    "footer": "Archivos manifest provenientes de ManifestHub (GitHub). No alojamos archivos directamente.",
    "dl_toast": "Todos los archivos se descargaron correctamente.",
    "search": "Buscar",
    "games": "Juegos",
    "language": "Idioma",
    "invalid_id": "Ingresa un App ID valido.",
    "error_search": "Error al buscar.",
    "jszip_error": "JSZip no se cargo. Recarga la pagina."
  }},
  "ca": { "name": "Català", "flag": "🏴", "t": {
    "subtitle": "Busca i descarrega fitxers .manifest de qualsevol joc de Steam",
    "search_placeholder": "Steam App ID (ex: 730)",
    "fetch_btn": "Cercar",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Introdueix un App ID per cercar fitxers .manifest a ManifestHub.",
    "welcome_sub": "Suporta mes de 62.000 jocs i DLCs.",
    "popular_label": "Populars:",
    "trending_title": "Jocs en Tendencia",
    "loading": "Cercant manifests...",
    "not_found": "No s'han trobat manifests per a l'App ID",
    "not_found_hint": "Encara no estan disponibles per a aquest joc.",
    "download_all": "Descarrega Tot (.zip)",
    "downloading": "Descarregant...",
    "manifests": "manifest(s)",
    "sources": "font(s)",
    "btn_download": "Descarregar",
    "footer": "Fitxers manifest provinents de ManifestHub (GitHub). No allotgem fitxers directament.",
    "dl_t": "Tots els fitxers s'han descarregat correctament.",
    "search": "Cercar",
    "games": "Jocs",
    "language": "Idioma",
    "invalid_id": "Introdueix un App ID valid.",
    "error_search": "Error al cercar.",
    "jszip_error": "JSZip no s'ha carregat. Recarrega la pagina."
  }},
  "eu": { "name": "Euskara", "flag": "🏴", "t": {
    "subtitle": "Bilatu eta deskargatu .manifest fitxeroak edozein Steam jokotik",
    "search_placeholder": "Steam App ID (adib: 730)",
    "fetch_btn": "Bilatu",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Sartu App ID bat .manifest fitxeroak ManifestHub-en bilatzeko.",
    "welcome_sub": "62.000 joko eta DLC baino gehiago onartzen ditu.",
    "popular_label": "Popularrak:",
    "trending_title": "Joera Duten Jokoak",
    "loading": "Manifestak bilatzen...",
    "not_found": "Ez da manifest aurkitu App ID honentzat",
    "not_found_hint": "Ondorengo joko honetan oraindik eskuragarri egon daitezke.",
    "download_all": "Denak Deskargatu (.zip)",
    "downloading": "Deskargatzen...",
    "manifests": "manifest(s)",
    "sources": "iturri(s)",
    "btn_download": "Deskargatu",
    "footer": "Manifest fitxeroak ManifestHub-etik (GitHub). Ez ditugu fitxeroak zuzenean ostatatzen.",
    "dl_t": "Fitxero guztiak ondo deskargatu dira.",
    "search": "Bilatu",
    "games": "Jokoak",
    "language": "Hizkuntza",
    "invalid_id": "Sartu App ID baliozko bat.",
    "error_search": "Bilaketa errorea.",
    "jszip_error": "JSZip kargatu ez. Berriz kargatu orria."
  }},
  "gl": { "name": "Galego", "flag": "🏴", "t": {
    "subtitle": "Busca e descarga ficheiros .manifest de calquera xogo de Steam",
    "search_placeholder": "Steam App ID (ex: 730)",
    "fetch_btn": "Buscar",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Introduce un App ID para buscar ficheiros .manifest en ManifestHub.",
    "welcome_sub": "Soporta mais de 62.000 xogos e DLCs.",
    "popular_label": "Populares:",
    "trending_title": "Xogos en Tendencia",
    "loading": "Buscando manifests...",
    "not_found": "Non se atoparon manifests para o App ID",
    "not_found_hint": "Ainda non estan dispoñibles para este xogo.",
    "download_all": "Descargar Todo (.zip)",
    "downloading": "Descargando...",
    "manifests": "manifest(s)",
    "sources": "fonte(s)",
    "btn_download": "Descargar",
    "footer": "Ficheiros manifest provenientes de ManifestHub (GitHub). Non aloxamos ficheiros directamente.",
    "dl_t": "Todos os ficheiros descargaronse correctamente.",
    "search": "Buscar",
    "games": "Xogos",
    "language": "Idioma",
    "invalid_id": "Introduce un App ID valido.",
    "error_search": "Erro na busqueda.",
    "jszip_error": "JSZip non se cargo. Recarga a pagina."
  }},
  "an": { "name": "Andaluz", "flag": "🟢", "t": {
    "subtitle": "Busca y descarga lo' archivo' .manifest de na' juego de Steam, ¡allah!...",
    "search_placeholder": "El App ID, ¿cuáe? (ej: 730)",
    "fetch_btn": "¡A buscalo!",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Meté un App ID pa buscar archivo' .manifest en ManifestHub, ¡vamos!",
    "welcome_sub": "Soporta más de 62.000 juego' y DLC, ¡que son na'!",
    "popular_label": "Los más vistos:",
    "trending_title": "Lo' que van aora",
    "loading": "Buscando los manifest, espérate un poco...",
    "not_found": "No hay na' de manifests pal App ID",
    "not_found_hint": "Pue que aún no los hayan puesto, ¡espérate que ya llegan!",
    "download_all": "Descargar too (.zip)",
    "downloading": "Descargando... ¡va que va!",
    "manifests": "manifest",
    "sources": "fuente(s)",
    "btn_download": "¡Descárgalo!",
    "footer": "Los archivo' manifest son de ManifestHub (GitHub). Nosotros no guardamos na', ¡eh!",
    "dl_t": "¡Too descargao! ¡A disfrutalo, tío!",
    "search": "Buscar",
    "games": "Juego'",
    "language": "El idioma",
    "invalid_id": "El App ID tien que ser un numero, ¡no me vengas con na'!",
    "error_search": "Se ha liao pavo al buscar, ¡otra vez!",
    "jszip_error": "No se ha cargo el JSZip. Dale a la pagina otra ve', ¡porfa!"
  }},
  "fr": { "name": "Français", "flag": "🇫🇷", "t": {
    "subtitle": "Trouvez et téléchargez les fichiers .manifest de n'importe quel jeu Steam",
    "search_placeholder": "Steam App ID (ex: 730)",
    "fetch_btn": "Rechercher",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Entrez un App ID pour rechercher des fichiers .manifest sur ManifestHub.",
    "welcome_sub": "Supporte plus de 62 000 jeux et DLC.",
    "popular_label": "Populaires :",
    "trending_title": "Jeux Tendance",
    "loading": "Recherche de manifests...",
    "not_found": "Aucun manifest trouvé pour l'App ID",
    "not_found_hint": "Ils ne sont peut-être pas encore disponibles pour ce jeu.",
    "download_all": "Tout Télécharger (.zip)",
    "downloading": "Téléchargement...",
    "manifests": "manifest(s)",
    "sources": "source(s)",
    "btn_download": "Télécharger",
    "footer": "Fichiers manifest provenant de ManifestHub (GitHub). Nous n'hébergeons pas les fichiers directement.",
    "dl_t": "Tous les fichiers ont été téléchargés avec succès.",
    "search": "Rechercher",
    "games": "Jeux",
    "language": "Langue",
    "invalid_id": "Entrez un App ID valide.",
    "error_search": "Erreur de recherche.",
    "jszip_error": "JSZip na pas pu etre charge. Rechargez la page."
  }},
  "de": { "name": "Deutsch", "flag": "🇩🇪", "t": {
    "subtitle": "Finden und laden Sie .manifest-Dateien jedes Steam-Spiels herunter",
    "search_placeholder": "Steam App ID (z.B. 730)",
    "fetch_btn": "Suchen",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Geben Sie eine App ID ein, um nach .manifest-Dateien in ManifestHub zu suchen.",
    "welcome_sub": "Unterstützt über 62.000 Spiele und DLCs.",
    "popular_label": "Beliebt:",
    "trending_title": "Beliebte Spiele",
    "loading": "Manifests werden gesucht...",
    "not_found": "Keine Manifests für App ID gefunden",
    "not_found_hint": "Sie sind möglicherweise noch nicht für dieses Spiel verfügbar.",
    "download_all": "Alles Herunterladen (.zip)",
    "downloading": "Herunterladen...",
    "manifests": "Manifest(s)",
    "sources": "Quelle(n)",
    "btn_download": "Herunterladen",
    "footer": "Manifest-Dateien von ManifestHub (GitHub). Wir hosten keine Dateien direkt.",
    "dl_t": "Alle Dateien erfolgreich heruntergeladen.",
    "search": "Suchen",
    "games": "Spiele",
    "language": "Sprache",
    "invalid_id": "Geben Sie eine gultige App ID ein.",
    "error_search": "Suchfehler.",
    "jszip_error": "JSZip konnte nicht geladen werden. Seite neu laden."
  }},
  "it": { "name": "Italiano", "flag": "🇮🇹", "t": {
    "subtitle": "Trova e scarica i file .manifest di qualsiasi gioco Steam",
    "search_placeholder": "Steam App ID (es: 730)",
    "fetch_btn": "Cerca",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Inserisci un App ID per cercare file .manifest su ManifestHub.",
    "welcome_sub": "Supporta oltre 62.000 giochi e DLC.",
    "popular_label": "Popolari:",
    "trending_title": "Giochi di Tendenza",
    "loading": "Ricerca manifest...",
    "not_found": "Nessun manifest trovato per l'App ID",
    "not_found_hint": "Potrebbero non essere ancora disponibili per questo gioco.",
    "download_all": "Scarica Tutto (.zip)",
    "downloading": "Scaricamento...",
    "manifests": "manifest(s)",
    "sources": "fonte(i)",
    "btn_download": "Scarica",
    "footer": "File manifest provenienti da ManifestHub (GitHub). Non ospitiamo direttamente i file.",
    "dl_t": "Tutti i file scaricati con successo.",
    "search": "Cerca",
    "games": "Giochi",
    "language": "Lingua",
    "invalid_id": "Inserisci un App ID valido.",
    "error_search": "Errore di ricerca.",
    "jszip_error": "JSZip non si e caricato. Ricarica la pagina."
  }},
  "pt": { "name": "Português", "flag": "🇵🇹", "t": {
    "subtitle": "Encontre e descarregue ficheiros .manifest de qualquer jogo Steam",
    "search_placeholder": "Steam App ID (ex: 730)",
    "fetch_btn": "Pesquisar",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Introduza um App ID para procurar ficheiros .manifest no ManifestHub.",
    "welcome_sub": "Suporta mais de 62.000 jogos e DLCs.",
    "popular_label": "Populares:",
    "trending_title": "Jogos em Tendência",
    "loading": "A procurar manifests...",
    "not_found": "Nenhum manifest encontrado para o App ID",
    "not_found_hint": "Ainda não estão disponíveis para este jogo.",
    "download_all": "Transferir Tudo (.zip)",
    "downloading": "A transferir...",
    "manifests": "manifest(s)",
    "sources": "fonte(s)",
    "btn_download": "Transferir",
    "footer": "Ficheiros manifest provenientes do ManifestHub (GitHub). Não alojamos ficheiros diretamente.",
    "dl_t": "Todos os ficheiros transferidos com sucesso.",
    "search": "Pesquisar",
    "games": "Jogos",
    "language": "Idioma",
    "invalid_id": "Introduza um App ID valido.",
    "error_search": "Erro ao pesquisar.",
    "jszip_error": "JSZip falhou ao carregar. Recarregue a pagina."
  }},
  "br": { "name": "Português (BR)", "flag": "🇧🇷", "t": {
    "subtitle": "Encontre e baixe arquivos .manifest de qualquer jogo da Steam",
    "search_placeholder": "Steam App ID (ex: 730)",
    "fetch_btn": "Buscar",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Digite um App ID para buscar arquivos .manifest no ManifestHub.",
    "welcome_sub": "Suporta mais de 62.000 jogos e DLCs.",
    "popular_label": "Populares:",
    "trending_title": "Jogos em Alta",
    "loading": "Procurando manifests...",
    "not_found": "Nenhum manifest encontrado para o App ID",
    "not_found_hint": "Eles podem ainda não estar disponíveis para este jogo.",
    "download_all": "Baixar Tudo (.zip)",
    "downloading": "Baixando...",
    "manifests": "manifest(s)",
    "sources": "fonte(s)",
    "btn_download": "Baixar",
    "footer": "Arquivos manifest provenientes do ManifestHub (GitHub). Não hospedamos arquivos diretamente.",
    "dl_t": "Todos os arquivos baixados com sucesso.",
    "search": "Buscar",
    "games": "Jogos",
    "language": "Idioma",
    "invalid_id": "Digite um App ID valido.",
    "error_search": "Erro ao buscar.",
    "jszip_error": "Falha ao carregar o JSZip. Recarregue a pagina."
  }},
  "nl": { "name": "Nederlands", "flag": "🇳🇱", "t": {
    "subtitle": "Zoek en download .manifest-bestanden van elk Steam-spel",
    "search_placeholder": "Steam App ID (bijv. 730)",
    "fetch_btn": "Zoeken",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Voer een App ID in om naar .manifest-bestanden te zoeken in ManifestHub.",
    "welcome_sub": "Ondersteunt meer dan 62.000 spellen en DLC's.",
    "popular_label": "Populair:",
    "trending_title": "Trending Spellen",
    "loading": "Manifests zoeken...",
    "not_found": "Geen manifests gevonden voor App ID",
    "not_found_hint": "Ze zijn mogelijk nog niet beschikbaar voor dit spel.",
    "download_all": "Alles Downloaden (.zip)",
    "downloading": "Downloaden...",
    "manifests": "manifest(s)",
    "sources": "bron(nen)",
    "btn_download": "Downloaden",
    "footer": "Manifest-bestanden van ManifestHub (GitHub). We hosten geen bestanden direct.",
    "dl_t": "Alle bestanden succesvol gedownload.",
    "search": "Zoeken",
    "games": "Spellen",
    "language": "Taal",
    "invalid_id": "Voer een geldige App ID in.",
    "error_search": "Zoekfout.",
    "jszip_error": "JSZip kon niet laden. Vernieuw de pagina."
  }},
  "pl": { "name": "Polski", "flag": "🇵🇱", "t": {
    "subtitle": "Znajdz i pobierz pliki .manifest z dowolnej gry Steam",
    "search_placeholder": "Steam App ID (np. 730)",
    "fetch_btn": "Szukaj",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Wprowadź App ID, aby szukać plików .manifest w ManifestHub.",
    "welcome_sub": "Obsługuje ponad 62 000 gier i DLC.",
    "popular_label": "Popularne:",
    "trending_title": "Popularne Gry",
    "loading": "Szukanie manifestów...",
    "not_found": "Nie znaleziono manifestów dla App ID",
    "not_found_hint": "Mogą jeszcze nie być dostępne dla tej gry.",
    "download_all": "Pobierz Wszystko (.zip)",
    "downloading": "Pobieranie...",
    "manifests": "manifest(y)",
    "sources": "źródła",
    "btn_download": "Pobierz",
    "footer": "Pliki manifest z ManifestHub (GitHub). Nie hostujemy plików bezpośrednio.",
    "dl_t": "Wszystkie pliki pobrane pomyślnie.",
    "search": "Szukaj",
    "games": "Gry",
    "language": "Język",
    "invalid_id": "Wprowadz poprawny App ID.",
    "error_search": "Blad wyszukiwania.",
    "jszip_error": "JSZip nie mogl zostac zaladowany. Odswiez strone."
  }},
  "ru": { "name": "Русский", "flag": "🇷🇺", "t": {
    "subtitle": "Найдите и скачайте файлы .manifest из любой игры Steam",
    "search_placeholder": "Steam App ID (напр. 730)",
    "fetch_btn": "Найти",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Введите App ID для поиска файлов .manifest в ManifestHub.",
    "welcome_sub": "Поддерживает более 62 000 игр и DLC.",
    "popular_label": "Популярные:",
    "trending_title": "Популярные Игры",
    "loading": "Поиск манифестов...",
    "not_found": "Манифесты не найдены для App ID",
    "not_found_hint": "Они могут быть ещё недоступны для этой игры.",
    "download_all": "Скачать Всё (.zip)",
    "downloading": "Загрузка...",
    "manifests": "манифест(ы)",
    "sources": "источник(и)",
    "btn_download": "Скачать",
    "footer": "Файлы манифестов из ManifestHub (GitHub). Мы не размещаем файлы напрямую.",
    "dl_t": "Все файлы успешно загружены.",
    "search": "Найти",
    "games": "Игры",
    "language": "Язык",
    "invalid_id": "Vvedite pravilnyy App ID.",
    "error_search": "Oshibka poiska.",
    "jszip_error": "JSZip ne udalos zagruzit. Obnovite stranitsu."
  }},
  "uk": { "name": "Українська", "flag": "🇺🇦", "t": {
    "subtitle": "Знайдіть та завантажте файли .manifest з будь-якої гри Steam",
    "search_placeholder": "Steam App ID (напр. 730)",
    "fetch_btn": "Знайти",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Введіть App ID для пошуку файлів .manifest у ManifestHub.",
    "welcome_sub": "Підтримує понад 62 000 ігор та DLC.",
    "popular_label": "Популярні:",
    "trending_title": "Популярні Ігри",
    "loading": "Пошук маніфестів...",
    "not_found": "Маніфести не знайдені для App ID",
    "not_found_hint": "Вони можуть бути ще недоступні для цієї гри.",
    "download_all": "Завантажити Все (.zip)",
    "downloading": "Завантаження...",
    "manifests": "маніфест(и)",
    "sources": "джерело(а)",
    "btn_download": "Завантажити",
    "footer": "Файли маніфестів з ManifestHub (GitHub). Ми не розміщуємо файли безпосередньо.",
    "dl_t": "Усі файли успішно завантажено.",
    "search": "Знайти",
    "games": "Ігри",
    "language": "Мова",
    "invalid_id": "Vvedit pravyl'nyy App ID.",
    "error_search": "Pomylka poshuku.",
    "jszip_error": "JSZip ne vdalosya zavantazhyty. Onovit storinku."
  }},
  "tr": { "name": "Türkçe", "flag": "🇹🇷", "t": {
    "subtitle": "Herhangi bir Steam oyunundan .manifest dosyalarını bulun ve indirin",
    "search_placeholder": "Steam App ID (örn. 730)",
    "fetch_btn": "Ara",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "ManifestHub'da .manifest dosyaları bulmak için bir App ID girin.",
    "welcome_sub": "62.000'den fazla oyunu ve DLC'yi destekler.",
    "popular_label": "Popüler:",
    "trending_title": "Gündemdekiler",
    "loading": "Manifestler aranıyor...",
    "not_found": "App ID için manifest bulunamadı",
    "not_found_hint": "Bu oyun için henüz mevcut olmayabilir.",
    "download_all": "Tümünü İndir (.zip)",
    "downloading": "İndiriliyor...",
    "manifests": "manifest",
    "sources": "kaynak(lar)",
    "btn_download": "İndir",
    "footer": "Manifest dosyaları ManifestHub'dan (GitHub). Dosyaları doğrudan barındırmıyoruz.",
    "dl_t": "Tüm dosyalar başarıyla indirildi.",
    "search": "Ara",
    "games": "Oyunlar",
    "language": "Dil",
    "invalid_id": "Gecerli bir App ID girin.",
    "error_search": "Arama hatasi.",
    "jszip_error": "JSZip yuklenemedi. Sayfayi yenileyin."
  }},
  "ar": { "name": "العربية", "flag": "🇸🇦", "t": {
    "subtitle": "ابحث وقم بتنزيل ملفات .manifest من أي لعبة على Steam",
    "search_placeholder": "Steam App ID (مثال: 730)",
    "fetch_btn": "بحث",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "أدخل App ID للبحث عن ملفات .manifest في ManifestHub.",
    "welcome_sub": "يدعم أكثر من 62,000 لعبة وDLC.",
    "popular_label": "الرائج:",
    "trending_title": "ألعاب رائجة",
    "loading": "جارٍ البحث عن المانيفستات...",
    "not_found": "لم يتم العثور على مانيفستات لـ App ID",
    "not_found_hint": "قد لا تكون متاحة لهذه اللعبة بعد.",
    "download_all": "تنزيل الكل (.zip)",
    "downloading": "جارٍ التنزيل...",
    "manifests": "مانيفست",
    "sources": "مصدر(ات)",
    "btn_download": "تنزيل",
    "footer": "ملفات مانيفست من ManifestHub (GitHub). لا نستضيف الملفات مباشرة.",
    "dl_t": "تم تنزيل جميع الملفات بنجاح.",
    "search": "بحث",
    "games": "ألعاب",
    "language": "اللغة",
    "invalid_id": "أدخل App ID صالح.",
    "error_search": "خطأ في البحث.",
    "jszip_error": "فشل تحميل JSZip. أعد تحميل الصفحة."
  }},
  "zh": { "name": "中文", "flag": "🇨🇳", "t": {
    "subtitle": "查找并下载任何Steam游戏的.manifest文件",
    "search_placeholder": "Steam App ID (例如 730)",
    "fetch_btn": "搜索",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "输入App ID在ManifestHub中搜索.manifest文件。",
    "welcome_sub": "支持超过62,000款游戏和DLC。",
    "popular_label": "热门：",
    "trending_title": "热门游戏",
    "loading": "正在搜索manifests...",
    "not_found": "未找到App ID的manifests",
    "not_found_hint": "它们可能尚未对此游戏可用。",
    "download_all": "全部下载 (.zip)",
    "downloading": "下载中...",
    "manifests": "manifest(s)",
    "sources": "来源",
    "btn_download": "下载",
    "footer": "Manifest文件来自ManifestHub (GitHub)。我们不直接托管文件。",
    "dl_t": "所有文件下载成功。",
    "search": "搜索",
    "games": "游戏",
    "language": "语言",
    "invalid_id": "请输入有效的App ID。",
    "error_search": "搜索错误。",
    "jszip_error": "JSZip加载失败，请刷新页面。"
  }},
  "tw": { "name": "繁體中文", "flag": "🇹🇼", "t": {
    "subtitle": "搜尋並下載任何Steam遊戲的.manifest檔案",
    "search_placeholder": "Steam App ID (例如 730)",
    "fetch_btn": "搜尋",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "輸入App ID在ManifestHub中搜尋.manifest檔案。",
    "welcome_sub": "支援超過62,000款遊戲和DLC。",
    "popular_label": "熱門：",
    "trending_title": "熱門遊戲",
    "loading": "正在搜尋manifests...",
    "not_found": "未找到App ID的manifests",
    "not_found_hint": "它們可能尚未對此遊戲可用。",
    "download_all": "全部下載 (.zip)",
    "downloading": "下載中...",
    "manifests": "manifest(s)",
    "sources": "來源",
    "btn_download": "下載",
    "footer": "Manifest檔案來自ManifestHub (GitHub)。我們不直接託管檔案。",
    "dl_t": "所有檔案下載成功。",
    "search": "搜尋",
    "games": "遊戲",
    "language": "語言",
    "invalid_id": "請輸入有效的App ID。",
    "error_search": "搜尋錯誤。",
    "jszip_error": "JSZip載入失敗，請重新整理頁面。"
  }},
  "ja": { "name": "日本語", "flag": "🇯🇵", "t": {
    "subtitle": "Steamゲームの.manifestファイルを検索してダウンロード",
    "search_placeholder": "Steam App ID (例: 730)",
    "fetch_btn": "検索",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "App IDを入力してManifestHubで.manifestファイルを検索。",
    "welcome_sub": "62,000以上のゲームとDLCをサポート。",
    "popular_label": "人気：",
    "trending_title": "トレンドゲーム",
    "loading": "Manifestを検索中...",
    "not_found": "App IDのmanifestが見つかりませんでした",
    "not_found_hint": "このゲームではまだ利用できない可能性があります。",
    "download_all": "すべてダウンロード (.zip)",
    "downloading": "ダウンロード中...",
    "manifests": "manifest(s)",
    "sources": "ソース",
    "btn_download": "ダウンロード",
    "footer": "ManifestファイルはManifestHub (GitHub)から。直接ホストしていません。",
    "dl_t": "すべてのファイルのダウンロードに成功しました。",
    "search": "検索",
    "games": "ゲーム",
    "language": "言語",
    "invalid_id": "有効なApp IDを入力してください。",
    "error_search": "検索エラー。",
    "jszip_error": "JSZipの読み込みに失敗しました。ページを再読み込みしてください。"
  }},
  "ko": { "name": "한국어", "flag": "🇰🇷", "t": {
    "subtitle": "모든 Steam 게임의 .manifest 파일을 찾고 다운로드하세요",
    "search_placeholder": "Steam App ID (예: 730)",
    "fetch_btn": "검색",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "App ID를 입력하여 ManifestHub에서 .manifest 파일을 검색하세요.",
    "welcome_sub": "62,000개 이상의 게임과 DLC를 지원합니다.",
    "popular_label": "인기:",
    "trending_title": "인기 게임",
    "loading": "Manifest 검색 중...",
    "not_found": "App ID에 대한 manifest를 찾을 수 없습니다",
    "not_found_hint": "이 게임에는 아직 사용 가능하지 않을 수 있습니다.",
    "download_all": "전체 다운로드 (.zip)",
    "downloading": "다운로드 중...",
    "manifests": "manifest(s)",
    "sources": "소스",
    "btn_download": "다운로드",
    "footer": "Manifest 파일은 ManifestHub (GitHub)에서 제공됩니다. 직접 호스팅하지 않습니다.",
    "dl_t": "모든 파일이 성공적으로 다운로드되었습니다.",
    "search": "검색",
    "games": "게임",
    "language": "언어",
    "invalid_id": "유효한 App ID를 입력하세요.",
    "error_search": "검색 오류.",
    "jszip_error": "JSZip 로드 실패. 페이지를 새로고침하세요."
  }},
  "hi": { "name": "हिन्दी", "flag": "🇮🇳", "t": {
    "subtitle": "किसी भी Steam गेम से .manifest फ़ाइलें खोजें और डाउनलोड करें",
    "search_placeholder": "Steam App ID (जैसे 730)",
    "fetch_btn": "खोजें",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "ManifestHub में .manifest फ़ाइलें खोजने के लिए App ID दर्ज करें।",
    "welcome_sub": "62,000 से अधिक गेम और DLC का समर्थन करता है।",
    "popular_label": "लोकप्रिय:",
    "trending_title": "ट्रेंडिंग गेम",
    "loading": "Manifest खोज रहे हैं...",
    "not_found": "App ID के लिए manifest नहीं मिले",
    "not_found_hint": "वे इस गेम के लिए अभी उपलब्ध नहीं हो सकते।",
    "download_all": "सभी डाउनलोड करें (.zip)",
    "downloading": "डाउनलोड हो रहा है...",
    "manifests": "manifest(s)",
    "sources": "स्रोत",
    "btn_download": "डाउनलोड",
    "footer": "Manifest फ़ाइलें ManifestHub (GitHub) से। हम सीधे फ़ाइलें होस्ट नहीं करते।",
    "dl_t": "सभी फ़ाइलें सफलतापूर्वक डाउनलोड हो गईं।",
    "search": "खोजें",
    "games": "गेम",
    "language": "भाषा",
    "invalid_id": "एक मान्य App ID दर्ज करें।",
    "error_search": "खोज त्रुटि।",
    "jszip_error": "JSZip लोड नहीं हो सका। पेज रीलोड करें।"
  }},
  "id": { "name": "Indonesia", "flag": "🇮🇩", "t": {
    "subtitle": "Cari dan unduh file .manifest dari game Steam mana pun",
    "search_placeholder": "Steam App ID (misal: 730)",
    "fetch_btn": "Cari",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Masukkan App ID untuk mencari file .manifest di ManifestHub.",
    "welcome_sub": "Mendukung lebih dari 62.000 game dan DLC.",
    "popular_label": "Populer:",
    "trending_title": "Game Trending",
    "loading": "Mencari manifest...",
    "not_found": "Manifest tidak ditemukan untuk App ID",
    "not_found_hint": "Mungkin belum tersedia untuk game ini.",
    "download_all": "Unduh Semua (.zip)",
    "downloading": "Mengunduh...",
    "manifests": "manifest(s)",
    "sources": "sumber",
    "btn_download": "Unduh",
    "footer": "File manifest dari ManifestHub (GitHub). Kami tidak menghosting file secara langsung.",
    "dl_t": "Semua file berhasil diunduh.",
    "search": "Cari",
    "games": "Game",
    "language": "Bahasa",
    "invalid_id": "Masukkan App ID yang valid.",
    "error_search": "Kesalahan pencarian.",
    "jszip_error": "JSZip gagal dimuat. Muat ulang halaman."
  }},
  "vi": { "name": "Tiếng Việt", "flag": "🇻🇳", "t": {
    "subtitle": "Tìm và tải file .manifest từ bất kỳ game Steam nào",
    "search_placeholder": "Steam App ID (vd: 730)",
    "fetch_btn": "Tìm",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Nhập App ID để tìm file .manifest trên ManifestHub.",
    "welcome_sub": "Hỗ trợ hơn 62,000 game và DLC.",
    "popular_label": "Phổ biến:",
    "trending_title": "Game Xu hướng",
    "loading": "Đang tìm manifest...",
    "not_found": "Không tìm thấy manifest cho App ID",
    "not_found_hint": "Chúng có thể chưa khả dụng cho game này.",
    "download_all": "Tải Tất Cả (.zip)",
    "downloading": "Đang tải...",
    "manifests": "manifest(s)",
    "sources": "nguồn",
    "btn_download": "Tải",
    "footer": "File manifest từ ManifestHub (GitHub). Chúng tôi không host file trực tiếp.",
    "dl_t": "Tất cả file đã tải thành công.",
    "search": "Tìm",
    "games": "Game",
    "language": "Ngôn ngữ",
    "invalid_id": "Nhap App ID hop le.",
    "error_search": "Loi tim kiem.",
    "jszip_error": "JSZip tai that bai. Tai lai trang."
  }},
  "th": { "name": "ไทย", "flag": "🇹🇭", "t": {
    "subtitle": "ค้นหาและดาวน์โหลดไฟล์ .manifest จากเกม Steam ใดก็ได้",
    "search_placeholder": "Steam App ID (เช่น 730)",
    "fetch_btn": "ค้นหา",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "ป้อน App ID เพื่อค้นหาไฟล์ .manifest ใน ManifestHub",
    "welcome_sub": "รองรับเกมและ DLC มากกว่า 62,000 เกม",
    "popular_label": "ยอดนิยม:",
    "trending_title": "เกมยอดนิยม",
    "loading": "กำลังค้นหา manifests...",
    "not_found": "ไม่พบ manifests สำหรับ App ID",
    "not_found_hint": "อาจยังไม่มีให้บริการสำหรับเกมนี้",
    "download_all": "ดาวน์โหลดทั้งหมด (.zip)",
    "downloading": "กำลังดาวน์โหลด...",
    "manifests": "manifest(s)",
    "sources": "แหล่งที่มา",
    "btn_download": "ดาวน์โหลด",
    "footer": "ไฟล์ manifest จาก ManifestHub (GitHub) เราไม่ได้โฮสต์ไฟล์โดยตรง",
    "dl_t": "ดาวน์โหลดไฟล์ทั้งหมดสำเร็จ",
    "search": "ค้นหา",
    "games": "เกม",
    "language": "ภาษา",
    "invalid_id": "กรุณาใส่ App ID ที่ถูกต้อง",
    "error_search": "เกิดข้อผิดพลาดในการค้นหา",
    "jszip_error": "JSZip โหลดไม่สำเร็จ กรุณาโหลดหน้าใหม่"
  }},
  "sv": { "name": "Svenska", "flag": "🇸🇪", "t": {
    "subtitle": "Hitta och ladda ner .manifest-filer från alla Steam-spel",
    "search_placeholder": "Steam App ID (t.ex. 730)",
    "fetch_btn": "Sök",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Ange ett App ID för att söka efter .manifest-filer i ManifestHub.",
    "welcome_sub": "Stöder över 62 000 spel och DLCer.",
    "popular_label": "Populärt:",
    "trending_title": "Trendande Spel",
    "loading": "Söker manifests...",
    "not_found": "Inga manifests hittades för App ID",
    "not_found_hint": "De kanske inte är tillgängliga för detta spelet ännu.",
    "download_all": "Ladda Ner Allt (.zip)",
    "downloading": "Laddar ner...",
    "manifests": "manifest(s)",
    "sources": "källa(er)",
    "btn_download": "Ladda Ner",
    "footer": "Manifest-filer från ManifestHub (GitHub). Vi värdar inte filer direkt.",
    "dl_t": "Alla filer laddades ner.",
    "search": "Sök",
    "games": "Spel",
    "language": "Språk",
    "invalid_id": "Ange ett giltigt App ID.",
    "error_search": "Sökfel.",
    "jszip_error": "JSZip kunde inte laddas. Ladda om sidan."
  }},
  "da": { "name": "Dansk", "flag": "🇩🇰", "t": {
    "subtitle": "Find og download .manifest-filer fra ethvert Steam-spil",
    "search_placeholder": "Steam App ID (f.eks. 730)",
    "fetch_btn": "Søg",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Indtast en App ID for at søge efter .manifest-filer i ManifestHub.",
    "welcome_sub": "Understøtter over 62.000 spil og DLCer.",
    "popular_label": "Populære:",
    "trending_title": "Trendende Spil",
    "loading": "Søger manifests...",
    "not_found": "Ingen manifests fundet for App ID",
    "not_found_hint": "De er måske ikke tilgængelige for dette spil endnu.",
    "download_all": "Download Alle (.zip)",
    "downloading": "Downloader...",
    "manifests": "manifest(s)",
    "sources": "kilde(r)",
    "btn_download": "Download",
    "footer": "Manifest-filer fra ManifestHub (GitHub). Vi hoster ikke filer direkte.",
    "dl_t": "Alle filer downloadet succesfuldt.",
    "search": "Søg",
    "games": "Spil",
    "language": "Sprog",
    "invalid_id": "Indtast en gyldig App ID.",
    "error_search": "Søgningsfejl.",
    "jszip_error": "JSZip kunne ikke indlaeses. Genindlaes siden."
  }},
  "no": { "name": "Norsk", "flag": "🇳🇴", "t": {
    "subtitle": "Finn og last ned .manifest-filer fra ethvert Steam-spill",
    "search_placeholder": "Steam App ID (f.eks. 730)",
    "fetch_btn": "Søk",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Skriv inn en App ID for å søke etter .manifest-filer i ManifestHub.",
    "welcome_sub": "Støtter over 62 000 spill og DLC-er.",
    "popular_label": "Populære:",
    "trending_title": "Trendende Spill",
    "loading": "Søker manifests...",
    "not_found": "Ingen manifests funnet for App ID",
    "not_found_hint": "De er kanskje ikke tilgjengelige for dette spillet ennå.",
    "download_all": "Last Ned Alle (.zip)",
    "downloading": "Laster ned...",
    "manifests": "manifest(s)",
    "sources": "kilde(r)",
    "btn_download": "Last Ned",
    "footer": "Manifest-filer fra ManifestHub (GitHub). Vi hoster ikke filer direkte.",
    "dl_t": "Alle filer lastet ned.",
    "search": "Søk",
    "games": "Spill",
    "language": "Språk",
    "invalid_id": "Skriv inn en gyldig App ID.",
    "error_search": "Søkefeil.",
    "jszip_error": "JSZip kunne ikke lastes inn. Last inn siden pa nytt."
  }},
  "fi": { "name": "Suomi", "flag": "🇫🇮", "t": {
    "subtitle": "Etsi ja lataa .manifest-tiedostoja mistä tahansa Steam-pelistä",
    "search_placeholder": "Steam App ID (esim. 730)",
    "fetch_btn": "Hae",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Syötä App ID etsiäksesi .manifest-tiedostoja ManifestHubista.",
    "welcome_sub": "Tukee yli 62 000 peliä ja DLC:ta.",
    "popular_label": "Suosituimmat:",
    "trending_title": "Suositut Pelit",
    "loading": "Haetaan manifesteja...",
    "not_found": "Manifesteja ei löytynyt App ID:lle",
    "not_found_hint": "Ne eivät ehkä ole vielä saatavilla tälle pelille.",
    "download_all": "Lataa Kaikki (.zip)",
    "downloading": "Ladataan...",
    "manifests": "manifest(s)",
    "sources": "lähde(t)",
    "btn_download": "Lataa",
    "footer": "Manifest-tiedostot ManifestHubista (GitHub). Emme isännöi tiedostoja suoraan.",
    "dl_t": "Kaikki tiedostot ladattu onnistuneesti.",
    "search": "Hae",
    "games": "Pelit",
    "language": "Kieli",
    "invalid_id": "Syota kelvollinen App ID.",
    "error_search": "Hakuvirhe.",
    "jszip_error": "JSZipin lataaminen epaonnistui. Lataa sivu uudelleen."
  }},
  "el": { "name": "Ελληνικά", "flag": "🇬🇷", "t": {
    "subtitle": "Εύρεση και λήψη αρχείων .manifest από οποιοδήποτε παιχνίδι Steam",
    "search_placeholder": "Steam App ID (π.χ. 730)",
    "fetch_btn": "Αναζήτηση",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Εισάγετε ένα App ID για αναζήτηση αρχείων .manifest στο ManifestHub.",
    "welcome_sub": "Υποστηρίζει πάνω από 62.000 παιχνίδια και DLC.",
    "popular_label": "Δημοφιλή:",
    "trending_title": "Τάσεις Παιχνιδιών",
    "loading": "Αναζήτηση manifests...",
    "not_found": "Δεν βρέθηκαν manifests για το App ID",
    "not_found_hint": "Ίσως δεν είναι ακόμα διαθέσιμα για αυτό το παιχνίδι.",
    "download_all": "Λήψη Όλων (.zip)",
    "downloading": "Λήψη...",
    "manifests": "manifest(s)",
    "sources": "πηγή(ες)",
    "btn_download": "Λήψη",
    "footer": "Αρχία manifest από ManifestHub (GitHub). Δεν φιλοξενούμε αρχεία απευθείας.",
    "dl_t": "Όλα τα αρχία λήφθηκαν με επιτυχία.",
    "search": "Αναζήτηση",
    "games": "Παιχνίδια",
    "language": "Γλώσσα",
    "invalid_id": "Εισάγετε έγκυρο App ID.",
    "error_search": "Σφάλμα αναζήτησης.",
    "jszip_error": "Το JSZip απέτυχε να φορτωθεί. Επαναφορτώστε τη σελίδα."
  }},
  "cs": { "name": "Čeština", "flag": "🇨🇿", "t": {
    "subtitle": "Najděte a stáhněte soubory .manifest z jakékoli hry na Steamu",
    "search_placeholder": "Steam App ID (např. 730)",
    "fetch_btn": "Hledat",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Zadejte App ID pro vyhledávání souborů .manifest v ManifestHub.",
    "welcome_sub": "Podporuje přes 62 000 her a DLC.",
    "popular_label": "Populární:",
    "trending_title": "Trendující Hry",
    "loading": "Hledání manifestů...",
    "not_found": "Pro App ID nebyly nalezeny žádné manifesty",
    "not_found_hint": "Pro tuto hru nemusí být ještě k dispozici.",
    "download_all": "Stáhnout Vše (.zip)",
    "downloading": "Stahování...",
    "manifests": "manifest(y)",
    "sources": "zdroj(e)",
    "btn_download": "Stáhnout",
    "footer": "Manifest soubory z ManifestHub (GitHub). Soubory přímo nehospodáříme.",
    "dl_t": "Všechny soubory úspěšně staženy.",
    "search": "Hledat",
    "games": "Hry",
    "language": "Jazyk",
    "invalid_id": "Zadejte platne App ID.",
    "error_search": "Chyba vyhledavani.",
    "jszip_error": "JSZip se nepodarilo nacist. Obnovte stranku."
  }},
  "hu": { "name": "Magyar", "flag": "🇭🇺", "t": {
    "subtitle": "Keress és tölts le .manifest fájlokat bármely Steam játékból",
    "search_placeholder": "Steam App ID (pl. 730)",
    "fetch_btn": "Keresés",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Adj meg egy App ID-t a .manifest fájlok kereséséhez a ManifestHub-ban.",
    "welcome_sub": "Több mint 62 000 játékot és DLC-t támogat.",
    "popular_label": "Népszerű:",
    "trending_title": "Felkapott Játékok",
    "loading": "Manifestek keresése...",
    "not_found": "Nem találhatók manifestek a megadott App ID-hez",
    "not_found_hint": "Még nem érhetők el ehhez a játékhoz.",
    "download_all": "Összes Letöltése (.zip)",
    "downloading": "Letöltés...",
    "manifests": "manifest(ek)",
    "sources": "forrás(ok)",
    "btn_download": "Letöltés",
    "footer": "Manifest fájlok a ManifestHub-ról (GitHub). Nem közvetlenül tároljuk a fájlokat.",
    "dl_t": "Minden fájl sikeresen letöltve.",
    "search": "Keresés",
    "games": "Játékok",
    "language": "Nyelv",
    "invalid_id": "Adjon meg ervenyes App ID-t.",
    "error_search": "Keresesi hiba.",
    "jszip_error": "JSZip nem toltodott be. Toltse ujra az oldalt."
  }},
  "ro": { "name": "Română", "flag": "🇷🇴", "t": {
    "subtitle": "Găsiți și descărcați fișiere .manifest din orice joc Steam",
    "search_placeholder": "Steam App ID (ex: 730)",
    "fetch_btn": "Căutare",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Introduceți un App ID pentru a căuta fișiere .manifest în ManifestHub.",
    "welcome_sub": "Suportă peste 62.000 de jocuri și DLC-uri.",
    "popular_label": "Populare:",
    "trending_title": "Jocuri în Tendință",
    "loading": "Se caută manifests...",
    "not_found": "Nu s-au găsit manifests pentru App ID",
    "not_found_hint": "Este posibil să nu fie încă disponibile pentru acest joc.",
    "download_all": "Descarcă Tot (.zip)",
    "downloading": "Se descarcă...",
    "manifests": "manifest(e)",
    "sources": "sursă(e)",
    "btn_download": "Descarcă",
    "footer": "Fișiere manifest din ManifestHub (GitHub). Nu găzduim fișiere direct.",
    "dl_t": "Toate fișierele au fost descărcate cu succes.",
    "search": "Căutare",
    "games": "Jocuri",
    "language": "Limbă",
    "invalid_id": "Introduceti un App ID valid.",
    "error_search": "Eroare de cautare.",
    "jszip_error": "JSZip nu s-a incarcat. Reincarcati pagina."
  }},
  "sk": { "name": "Slovenčina", "flag": "🇸🇰", "t": {
    "subtitle": "Nájdite a stiahnite súbory .manifest z akejkoľvek hry na Steame",
    "search_placeholder": "Steam App ID (napr. 730)",
    "fetch_btn": "Hľadať",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Zadajte App ID na vyhľadávanie súborov .manifest v ManifestHub.",
    "welcome_sub": "Podporuje viac ako 62 000 hier a DLC.",
    "popular_label": "Populárne:",
    "trending_title": "Trendujúce Hry",
    "loading": "Hľadanie manifestov...",
    "not_found": "Pre App ID sa nenašli žiadne manifesty",
    "not_found_hint": "Pre túto hru nemusia byť ešte k dispozícii.",
    "download_all": "Stiahnuť Všetko (.zip)",
    "downloading": "Sťahovanie...",
    "manifests": "manifest(y)",
    "sources": "zdroj(e)",
    "btn_download": "Stiahnuť",
    "footer": "Manifest súbory z ManifestHub (GitHub). Súbory priamo nehospodárime.",
    "dl_t": "Všetky súbory úspešne stiahnuté.",
    "search": "Hľadať",
    "games": "Hry",
    "language": "Jazyk",
    "invalid_id": "Zadajte platne App ID.",
    "error_search": "Chyba vyhladavania.",
    "jszip_error": "JSZip sa nepodarilo nacitat. Obnovte stranku."
  }},
  "hr": { "name": "Hrvatski", "flag": "🇭🇷", "t": {
    "subtitle": "Pronađite i preuzmite .manifest datoteke iz bilo koje Steam igre",
    "search_placeholder": "Steam App ID (npr. 730)",
    "fetch_btn": "Traži",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Unesite App ID za traženje .manifest datoteka u ManifestHub.",
    "welcome_sub": "Podržava preko 62.000 igara i DLC-ova.",
    "popular_label": "Popularno:",
    "trending_title": "Trendi Igre",
    "loading": "Traženje manifesta...",
    "not_found": "Nema pronađenih manifesta za App ID",
    "not_found_hint": "Možda još nisu dostupni za ovu igru.",
    "download_all": "Preuzmi Sve (.zip)",
    "downloading": "Preuzimanje...",
    "manifests": "manifest(a)",
    "sources": "izvor(i)",
    "btn_download": "Preuzmi",
    "footer": "Manifest datoteke iz ManifestHub (GitHub). Ne hostamo datoteke izravno.",
    "dl_t": "Sve datoteke uspješno preuzete.",
    "search": "Traži",
    "games": "Igre",
    "language": "Jezik",
    "invalid_id": "Unesite valjani App ID.",
    "error_search": "Greska pretrage.",
    "jszip_error": "JSZip se nije mogao ucitati. Osvjezite stranicu."
  }},
  "sr": { "name": "Српски", "flag": "🇷🇸", "t": {
    "subtitle": "Пронађите и преузмите .manifest датотеке из било које Steam игре",
    "search_placeholder": "Steam App ID (нпр. 730)",
    "fetch_btn": "Претражи",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Унесите App ID за тражење .manifest датотека у ManifestHub.",
    "welcome_sub": "Подржава преко 62.000 игара и DLC-ова.",
    "popular_label": "Популарно:",
    "trending_title": "Тренд Игре",
    "loading": "Тражење манифеста...",
    "not_found": "Нема пронађених манифеста за App ID",
    "not_found_hint": "Можда још нisu доступни за ову игру.",
    "download_all": "Преузми Све (.zip)",
    "downloading": "Преузимање...",
    "manifests": "манифест(а)",
    "sources": "извор(и)",
    "btn_download": "Преузми",
    "footer": "Манифест датотеке из ManifestHub (GitHub). Не хостујемо датотеке директно.",
    "dl_t": "Све датотеке успешно преузете.",
    "search": "Претражи",
    "games": "Игре",
    "language": "Језик",
    "invalid_id": "Unesite ispravan App ID.",
    "error_search": "Greska pretrage.",
    "jszip_error": "JSZip nije mogao da se ucita. Osvezite stranicu."
  }},
  "bg": { "name": "Български", "flag": "🇧🇬", "t": {
    "subtitle": "Намерете и изтеглете .manifest файлове от всяка Steam игра",
    "search_placeholder": "Steam App ID (напр. 730)",
    "fetch_btn": "Търсене",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Въведете App ID за търсене на .manifest файлове в ManifestHub.",
    "welcome_sub": "Поддържа над 62 000 игри и DLC.",
    "popular_label": "Популярни:",
    "trending_title": "Тенденционни Игри",
    "loading": "Търсене на манифести...",
    "not_found": "Не са намерени манифести за App ID",
    "not_found_hint": "Все още може да не са налични за тази игра.",
    "download_all": "Изтегли Всичко (.zip)",
    "downloading": "Изтегляне...",
    "manifests": "манифест(а)",
    "sources": "източник(ци)",
    "btn_download": "Изтегли",
    "footer": "Манифест файлове от ManifestHub (GitHub). Не хостваме файлове директно.",
    "dl_t": "Всички файлове успешно изтеглени.",
    "search": "Търсене",
    "games": "Игри",
    "language": "Език",
    "invalid_id": "Vavedete validen App ID.",
    "error_search": "Greshka v tarseneto.",
    "jszip_error": "JSZip ne uspe da se zaredi. Osvete stranicata."
  }},
  "sl": { "name": "Slovenščina", "flag": "🇸🇮", "t": {
    "subtitle": "Poiščite in prenesite .manifest datoteke iz katerekoli Steam igre",
    "search_placeholder": "Steam App ID (npr. 730)",
    "fetch_btn": "Iskanje",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Vnesite App ID za iskanje .manifest datotek v ManifestHub.",
    "welcome_sub": "Podpira več kot 62.000 iger in DLC-jev.",
    "popular_label": "Priljubljeno:",
    "trending_title": "Naraščajoče Igre",
    "loading": "Iskanje manifestov...",
    "not_found": "Za App ID ni bilo najdenih manifestov",
    "not_found_hint": "Morda še niso na voljo za to igro.",
    "download_all": "Prenesi Vse (.zip)",
    "downloading": "Prenašanje...",
    "manifests": "manifest(i)",
    "sources": "vir(i)",
    "btn_download": "Prenesi",
    "footer": "Manifest datoteke iz ManifestHub (GitHub). Ne gostimo datotek neposredno.",
    "dl_t": "Vse datoteke uspešno prenesene.",
    "search": "Iskanje",
    "games": "Igre",
    "language": "Jezik",
    "invalid_id": "Vnesite veljaven App ID.",
    "error_search": "Napaka iskanja.",
    "jszip_error": "JSZip ni mogel naložiti. Osvežite stran."
  }},
  "lt": { "name": "Lietuvių", "flag": "🇱🇹", "t": {
    "subtitle": "Raskite ir atsisiųskite .manifest failus iš bet kurio Steam žaidimo",
    "search_placeholder": "Steam App ID (pvz. 730)",
    "fetch_btn": "Ieškoti",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Įveskite App ID ieškoti .manifest failų ManifestHub.",
    "welcome_sub": "Palaiko daugiau nei 62 000 žaidimų ir DLC.",
    "popular_label": "Populiarii:",
    "trending_title": "Trenduojantys Žaidimai",
    "loading": "Ieškoma manifestų...",
    "not_found": "App ID nerasta jokių manifestų",
    "not_found_hint": "Jie gali būti dar neprieinami šiam žaidimui.",
    "download_all": "Atsisiųsti Viską (.zip)",
    "downloading": "Atsisiunčiama...",
    "manifests": "manifest(ai)",
    "sources": "šaltinis(-iai)",
    "btn_download": "Atsisiųsti",
    "footer": "Manifest failai iš ManifestHub (GitHub). Mes nesaugome failų tiesiogiai.",
    "dl_t": "Visi failai sėkmingai atsisiųsti.",
    "search": "Ieškoti",
    "games": "Žaidimai",
    "language": "Kalba",
    "invalid_id": "Iveskite galiojanti App ID.",
    "error_search": "Paieskos klaida.",
    "jszip_error": "JSZip nepavyko ikelti. Atnaujinkite psl."
  }},
  "lv": { "name": "Latviešu", "flag": "🇱🇻", "t": {
    "subtitle": "Atrodiet un lejupielādējiet .manifest failus no jebkura Steam spēles",
    "search_placeholder": "Steam App ID (piem. 730)",
    "fetch_btn": "Meklēt",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Ievadiet App ID, lai meklētu .manifest failus ManifestHub.",
    "welcome_sub": "Atbalsta vairāk nekā 62 000 spēļu un DLC.",
    "popular_label": "Populāri:",
    "trending_title": "Trendējošas Spēles",
    "loading": "Meklē manifestus...",
    "not_found": "App ID nav atrasts neviens manifests",
    "not_found_hint": "Tie varētu vēl nebūt pieejami šai spēlei.",
    "download_all": "Lejupielādēt Visu (.zip)",
    "downloading": "Lejupielādē...",
    "manifests": "manifest(s)",
    "sources": "avots(-i)",
    "btn_download": "Lejupielādēt",
    "footer": "Manifest faili no ManifestHub (GitHub). Mēs neuzglabājam failus tieši.",
    "dl_t": "Visi faili veiksmīgi lejupielādēti.",
    "search": "Meklēt",
    "games": "Spēles",
    "language": "Valoda",
    "invalid_id": "Ievadiet derigu App ID.",
    "error_search": "Meklesanas kluda.",
    "jszip_error": "JSZip neizdevas ieladet. Atjaunojiet lapu."
  }},
  "et": { "name": "Eesti", "flag": "🇪🇪", "t": {
    "subtitle": "Leidke ja laadige alla .manifest failid igast Steam mängust",
    "search_placeholder": "Steam App ID (nt. 730)",
    "fetch_btn": "Otsi",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Sisestage App ID, et otsida .manifest faile ManifestHub.",
    "welcome_sub": "Toetab üle 62 000 mängu ja DLC.",
    "popular_label": "Populaarsed:",
    "trending_title": "Trendivad Mängud",
    "loading": "Otsitakse manifeste...",
    "not_found": "App ID jaoks ei leitud manifeste",
    "not_found_hint": "Need ei pruugi veel selle mängu jaoks kättesaadavad olla.",
    "download_all": "Laadi Kõik Alla (.zip)",
    "downloading": "Laaditakse alla...",
    "manifests": "manifest(id)",
    "sources": "allikas(-d)",
    "btn_download": "Laadi Alla",
    "footer": "Manifest failid ManifestHub-ist (GitHub). Me ei majuta faile otseselt.",
    "dl_t": "Kõik failid edukalt alla laaditud.",
    "search": "Otsi",
    "games": "Mängud",
    "language": "Keel",
    "invalid_id": "Sisestage kehtiv App ID.",
    "error_search": "Otsingu viga.",
    "jszip_error": "JSZip ei saanud laadida. Laadige leht uuesti."
  }},
  "cy": { "name": "Cymraeg", "flag": "🏴", "t": {
    "subtitle": "Canfod a lawrlwytho ffeiliau .manifest o unrhyw gêm Steam",
    "search_placeholder": "Steam App ID (e.e. 730)",
    "fetch_btn": "Chwilio",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Rhowch App ID i chwilio am ffeiliau .manifest yn ManifestHub.",
    "welcome_sub": "Cefnoga dros 62,000 o gemau a DLC.",
    "popular_label": "Poblogaidd:",
    "trending_title": "Gemau Tueddu",
    "loading": "Yn chwilio manifests...",
    "not_found": "Ni chafwyd manifests ar gyfer App ID",
    "not_found_hint": "Efallai nad ydynt ar gael i'r gêm hon eto.",
    "download_all": "Lawrlwytho'r Cyfan (.zip)",
    "downloading": "Yn lawrlwytho...",
    "manifests": "manifest(au)",
    "sources": "ffynhonnell(au)",
    "btn_download": "Lawrlwytho",
    "footer": "Ffeiliau manifest o ManifestHub (GitHub). Nid ydym yn cynnal ffeiliau'n uniongyrchol.",
    "dl_t": "Mae pob ffeil wedi'i lawrlwytho'n llwyddiannus.",
    "search": "Chwilio",
    "games": "Gemau",
    "language": "Iaith",
    "invalid_id": "Rhowch App ID dilys.",
    "error_search": "Gwall chwilio.",
    "jszip_error": "Methodd JSZip â llwytho. Ail-lwythwch y dudalen."
  }},
  "ga": { "name": "Gaeilge", "flag": "🇮🇪", "t": {
    "subtitle": "Faigh íoslódáil comhaid .manifest ó aon chluiche Steam",
    "search_placeholder": "Steam App ID (m.sh. 730)",
    "fetch_btn": "Cuardaigh",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Cuir isteach App ID chun comhaid .manifest a lorg i ManifestHub.",
    "welcome_sub": "Tacaíonn sé le breis agus 62,000 cluiche agus DLC.",
    "popular_label": "Coitianta:",
    "trending_title": "Cluichí TRENDING",
    "loading": "Ag lorg manifests...",
    "not_found": "Níor aimsíodh manifests don App ID",
    "not_found_hint": "B'fhéidir nach bhfuil siad ar fáil don chluiche seo fós.",
    "download_all": "Íoslódáil Uile (.zip)",
    "downloading": "Ag íoslódáil...",
    "manifests": "manifest(s)",
    "sources": "foinse(anna)",
    "btn_download": "Íoslódáil",
    "footer": "Comhaid manifest ó ManifestHub (GitHub). Ní óstáil muid comhaid go díreach.",
    "dl_t": "Íoslódáladh gach comhad go rathúil.",
    "search": "Cuardaigh",
    "games": "Cluichí",
    "language": "Teanga",
    "invalid_id": "Cuir isteach App ID baili.",
    "error_search": "Earraid cuardaigh.",
    "jszip_error": "Theip ar JSZip a loding. Athluchtaigh an leathanach."
  }},
  "oc": { "name": "Occitan", "flag": "🏴", "t": {
    "subtitle": "Trobar e telecargar fichièrs .manifest de quin jòc Steam que siá",
    "search_placeholder": "Steam App ID (per ex. 730)",
    "fetch_btn": "Recercar",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Entrar un App ID per recercar fichièrs .manifest dins ManifestHub.",
    "welcome_sub": "Supòrta mai de 62 000 jòcs e DLC.",
    "popular_label": "Populars:",
    "trending_title": "Jòcs Tendència",
    "loading": "Recèrca de manifests...",
    "not_found": "Cap de manifest pas trobat per l'App ID",
    "not_found_hint": "Son pas encara disponibles per aqueste jòc.",
    "download_all": "Telecargar Tot (.zip)",
    "downloading": "Telecargament...",
    "manifests": "manifest(s)",
    "sources": "font(s)",
    "btn_download": "Telecargar",
    "footer": "Fichièrs manifest de ManifestHub (GitHub). Hospedem pas de fichièrs dirèctament.",
    "dl_t": "Totas los fichièrs telecargats amb succès.",
    "search": "Recercar",
    "games": "Jòcs",
    "language": "Lenga",
    "invalid_id": "Entrar un App ID valent.",
    "error_search": "Error de recèrca.",
    "jszip_error": "JSZip a pas pogut èsser cargat. Tornatz cargar la pagina."
  }},
  "brb": { "name": "Brezhoneg", "flag": "🏴", "t": {
    "subtitle": "Kavout ha pellgargañ restroù .manifest eus gerioù Steam",
    "search_placeholder": "Steam App ID (e.e. 730)",
    "fetch_btn": "Klask",
    "welcome_title": "Steam Manifest Finder",
    "welcome_desc": "Enankañ App ID da glask restroù .manifest er ManifestHub.",
    "welcome_sub": "Skoret a ra muioc'h eget 62 000 ger ha DLC.",
    "popular_label": "Torr-c'horn:",
    "trending_title": "Gerioù war an Droad",
    "loading": "O klask manifests...",
    "not_found": "N'eus ket bet kavet manifests evit an App ID",
    "not_found_hint": "M'emañ muioc'h ne vint ket da gammañ evit ar ger-mañ.",
    "download_all": "Pellgargañ an holl (.zip)",
    "downloading": "O pellgargañ...",
    "manifests": "manifest(où)",
    "sources": "tarzh(ioù)",
    "btn_download": "Pellgargañ",
    "footer": "Restroù manifest eus ManifestHub (GitHub). N'emañ ket hosting restroù a-enep.",
    "dl_t": "An holl restroù bet pellgarguet mat.",
    "search": "Klask",
    "games": "Gerioù",
    "language": "Yezh",
    "invalid_id": "Enankit un App ID mat.",
    "error_search": "Fazi klask.",
    "jszip_error": "Ne v ket bet gallet kargañ JSZip. Adkargit ar pagin."
  }}
};